apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-first-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.3.0, pipelines.kubeflow.org/pipeline_compilation_time: '2021-01-24T17:14:09.976012',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A hello world pipeline.",
      "name": "My first pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.3.0}
spec:
  entrypoint: my-first-pipeline
  templates:
  - name: echo
    container:
      args: [echo "hello world"]
      command: [sh, -c]
      image: library/bash:4.4.23
  - name: my-first-pipeline
    dag:
      tasks:
      - {name: echo, template: echo}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
